n=int(input('digite um numero ='))
print('-'*15)
print(' 1 *',(n),'=',n*1)
print(' 2 *',(n),'=',n*2)
print(' 3 *',(n),'=',n*3)
print(' 4 *',(n),'=',n*4)
print(' 5 *',(n),'=',n*5)
print(' 6 *',(n),'=',n*6)
print(' 7 *',(n),'=',n*7)
print(' 8 *',(n),'=',n*8)
print(' 9 *',(n),'=',n*9)
print('10 *',(n),'=',n*10)
print('-'*15)